version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key-for-ci
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
    working_dir: /app/finassistant
    command: python manage.py runserver 0.0.0.0:8000

  test:
    build: .
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key-for-ci
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
    working_dir: /app/finassistant
    command: python -m pytest tests/ -v
