[build]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "cd finassistant && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn finassistant.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
PYTHON_VERSION = "3.12"
PYTHONPATH = "/app/finassistant"
