[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pip install -r requirements.txt && cd finassistant && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn finassistant.wsgi:application --bind 0.0.0.0:$PORT"

[env]
NODE_ENV = "production"
PYTHONPATH = "/app/finassistant"
